services:
  db:
    image: postgres:15-alpine
    container_name: sharenite-db
    environment:
      POSTGRES_USER: sharenite
      POSTGRES_PASSWORD: sharenite
      POSTGRES_DB: sharenite_development
    ports:
      - "5432:5432"
    volumes:
      - sharenite_db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: sharenite-redis
    ports:
      - "6379:6379"
    volumes:
      - sharenite_redis_data:/data

  kafka:
    image: bitnami/kafka:3.5
    container_name: sharenite-kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:9094,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - sharenite_kafka_data:/bitnami/kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: sharenite-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

volumes:
  sharenite_db_data:
  sharenite_redis_data:
  sharenite_kafka_data:
