FROM ruby:3.3.6-bookworm

ENV APP_PATH /var/app
ENV BUNDLER_VERSION 2.5.23
ENV BUNDLE_PATH /usr/local/bundle/gems
ENV TMP_PATH /tmp/
ENV RAILS_LOG_TO_STDOUT true

# copy entrypoint scripts and grant execution permissions
COPY ./entrypoint-docker-dev.sh /usr/local/bin/dev-entrypoint.sh
COPY ./entrypoint-docker-test.sh /usr/local/bin/test-entrypoint.sh
RUN chmod +x /usr/local/bin/dev-entrypoint.sh && chmod +x /usr/local/bin/test-entrypoint.sh

# install dependencies for application
RUN apt-get update -qq
RUN apt-get install -y ca-certificates curl gnupg
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
ARG NODE_MAJOR=20
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list

RUN apt-get update -qq \
    && apt-get install -y \ 
    ruby-dev \
    build-essential \
    libgmp-dev \
    libvips \
    nodejs \
    musl-dev \
    libreadline8 \
    libreadline-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man \
    && npm install -g yarn

RUN gem install bundler --version "$BUNDLER_VERSION" \
    && rm -rf $GEM_HOME/cache/*

# navigate to app directory
WORKDIR $APP_PATH

ENTRYPOINT [ "bundle", "exec" ]