FROM ruby:3.2.2

ENV APP_PATH /var/app
ENV BUNDLER_VERSION 2.4.17
ENV BUNDLE_PATH /usr/local/bundle/gems
ENV TMP_PATH /tmp/
ENV RAILS_LOG_TO_STDOUT true

# copy entrypoint scripts and grant execution permissions
COPY ./entrypoint-docker-dev.sh /usr/local/bin/dev-entrypoint.sh
COPY ./entrypoint-docker-test.sh /usr/local/bin/test-entrypoint.sh
RUN chmod +x /usr/local/bin/dev-entrypoint.sh && chmod +x /usr/local/bin/test-entrypoint.sh

# install dependencies for application
ARG NODE_MAJOR_VERSION=18
RUN curl -sL https://deb.nodesource.com/setup_$NODE_MAJOR_VERSION.x | bash -
RUN apt-get update -qq \
    && apt-get install -y \ 
    build-essential \
    libgmp-dev \
    libvips \
    nodejs \
    musl-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man \
    && npm install -g yarn

RUN gem install bundler --version "$BUNDLER_VERSION" \
    && rm -rf $GEM_HOME/cache/*

# navigate to app directory
WORKDIR $APP_PATH

ENTRYPOINT [ "bundle", "exec" ]